### ISSUE TITLE
Failed vagrant up: cannot access ‘.bashrc_iCub’

### ISSUE THREAD

**Issue by emilio-cartoni** [robotology/vagrant-icub#1]
Hi,
I've tried to create a virtualbox but debian-jessie-64, debian-wheezy-64  and ubuntu-trusty-64  all failed with the same error: _cannot access ‘.bashrc_iCub’_ when executing `chown` during the _vagrant up_ installation.
These are the last lines of the log when executing _vagrant up_ in ubuntu-trusty-64:

```
==> default: Cloning into 'icub-contrib-common'...
==> default: Adding user vagrant to sudo group..
==> default: Installing vagrant user enviroment..
==> default: chown: 
==> default: cannot access ‘.bashrc_iCub’
==> default: : No such file or directory
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

Trying to vagrant up a ubuntu-vivid-64 virtualbox instead failed because vagrant can't find ubuntu/vivid64 in the remote catalog.

**Comment by mbrunettini** [comment]
Fixed
