### ISSUE TITLE
Support for virtual machine with YARP and iCub software

### ISSUE THREAD

**Issue by gsaponaro** [robotology/vagrant-icub#4]
Hi @mbrunettini, I would like to use a Virtual Machine with yarp and icub-main software, on a machine where I cannot install packages system-wide, so I would like to have iCub software in a self-contained manner.

Is this repository still active?
Or is there another recommended strategy nowadays?

I gave a shot to `ubuntu-xenial-64` in this repository, but after running Vagrant I obtained the following error:
```
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.
The requested URL returned error: 404 Not Found
```

...likely because the provision file "https://git.robotology.eu/mbrunettini/icub-environment/raw/master/scripts/provision_icub_machine.sh" which is referenced by `Vagrantfile` does not exist anymore (after [this commit](https://git.robotology.eu/MBrunettini/icub-environment/commit/20571acb2866a1a9fe889ed411d9edfb922ebfdb)).

Thank you for any suggestion.

**Comment by vtikha** [comment]
Hi @gsaponaro , since you cannot install system wide packages, thus excluding docker Images etc, what about using the VM (Ubuntu) that was/is provided for the winter schools?. You can find it [here](https://github.com/vvv-school/vvv18/wiki/Before-arriving-at-VVV) with all the necessary instructions.

**Comment by mbrunettini** [comment]
Hi @gsaponaro the above issue is fixed now.
I'm adding ubuntu-disco and ubuntu-bionic as well as binaries only version: just need time to test them.

**Comment by gsaponaro** [comment]
@mbrunettini , thanks, I confirm that `ubuntu-xenial-64` works (after having installed `vagrant_2.2.6_x86_64.deb`, because the Vagrant from Ubuntu packages was too old).

@vtikha, thanks for the suggestion! Looks like a valuable alternative, with super detailed instructions.
